### ISSUE TITLE
Getting classname or subclass

### ISSUE THREAD

**Issue by lrosenth** [dhlab-basel/knora-api-js-lib#45]
In order to access the values, I need to now which subclass of ReadValue I get. ```obj.constructor.name``` does not work in minified code.

We should add an ```is A``property with symbols... (see my simplifier...)

https://github.com/dasch-swiss/knora-jsonld-simplify/blob/ad7cddbad28debb15863263aa83b3ad820d99d3f/src/KnoraValue.ts#L7-L10

**Comment by tobiasschweizer** [comment]
There is already a `type` property on each `ReadValue`:

https://github.com/dhlab-basel/knora-api-js-lib/blob/6bb8f562f4aa11a7250e815b1aee5262ec5defed/src/models/v2/resources/values/read-value.ts#L13

For a `ReadUriValue` that would be "http://api.knora.org/ontology/knora-api/v2#UriValue'". 

In addition, we could add symbols as suggested by you. Should they correspond to the class name?

**Comment by tobiasschweizer** [comment]
I think using symbols does not make much of a difference because casting is still necessary:

https://github.com/dhlab-basel/0807-mls-app-ng/blob/9d55a068766809eb8cce91ed8fa9071fec5f868e/src/app/services/knora-api.service.ts#L98-L102

What about a method like `<T>getValuesAsType(propertyIri: string, expectedType: dataType: { new(): T }): T[]`?

It would perform a check (is the value really an instance of T) and then do the cast.
